### ISSUE TITLE
taskstatus won't load in 0.2.1

### ISSUE THREAD

**Issue by twisted-pear** [tablet-mode/py3status-modules#2]
Since updating to 0.2.1 the taskstatus module won't load anymore. When i call `py3status -s -c .i3/status.conf --debug` "user method taskstatus failed (Type str doesn't support the buffer API)" gets written to syslog.

This happens with both py3status 1.6 and 2.0.

Other software:
- python 3.3.5
- taskwarrior 2.1.2

The error seems to occur in `Data.get_tasks()` in Line 61. A crude `str(e.output)` fixes the issue for me, but doesn't explain why I am having this problem and others (i.e. the author) do not. Unless of course you only tested it while having overdue tasks...

**Comment by t4k1t** [comment]
The problem is that I'm checking for a string in a bytestring, which obviously cannot work. A fix will be in version 0.3.0 which will hopefully be released sometime this week.

**Comment by t4k1t** [comment]
Version 0.3.0 has been released - please confirm the issue has been fixed.

**Comment by twisted-pear** [comment]
Tested 0.3.0 today, it's fixed now, thanks.
