### ISSUE TITLE
Option to hide mpdstatus when mpd is paused

### ISSUE THREAD

**Issue by ghost** [tablet-mode/py3status-modules#4]
Currently I'm using a `py3status` module to display the title of any Chromium tab that is playing audio (usually SoundCloud or YouTube). When I'm listening to something there, I usually pause mpd, but the mpdstatus line is always present.

So, I end up with a bar containing both, the title of the song that is currently being played in Chromium _and_ the title of the song paused in mpd.

It'd be nice to have an option to hide mpdstatus when mpd is paused, since I'm not interested in the name of a song that isn't being played, and I don't really use the mouse actions.

**Comment by t4k1t** [comment]
That's an interesting idea. I'll definitely think about it, maybe I could add a setting which controls on what kind of status the module would be hidden (e.g. stopped, paused) and then just display a pause character instead of the normal information.

**Comment by t4k1t** [comment]
Pushed e72ed5c6e61b8e3f1d859f62fe2796795fc10f00 to develop which implements this feature via the "hide_on_pause" setting - and I'm only like 9 months late.

**Comment by t4k1t** [comment]
Released in version 0.5.0
